import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/components/molecules/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "next13-masters",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Navigation />
				<main className="flex flex-col items-center justify-between p-24">
					{children}
				</main>
				<footer className="flex justify-center">
					<p>footer</p>
				</footer>
			</body>
		</html>
	);
}
